---
title: Pedro Tanaka
author: Pedro Tanaka
email: ''
description: Pedro Tanaka Website
baseurl: "/pedrotanaka.github.io/"
url: https://pedrotanaka.github.io
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
