---
title: Pedro Tanaka
author: Pedro Tanaka
email: ''
description: ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks
  feature. This theme provides a set of page-level components and a pre-configured
  Forestry Blocks UI that will empower content editors to construct their own webpages.
baseurl: "/pedrotanaka.github.io/"
url: https://pedrotanaka.github.io
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
